<Project Sdk="Dalamud.NET.Sdk/15.0.0">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>

    <AssemblyName>SquadronSolver</AssemblyName>
    <RootNamespace>SquadronSolver</RootNamespace>
    <Version>1.0.0.1</Version>
  </PropertyGroup>

</Project>